import React, { useState, useMemo } from 'react';
import { 
  Alert, 
  ScrollView, 
  Share, 
  StyleSheet, 
  Text, 
  TouchableOpacity, 
  View, 
  StatusBar,
  SafeAreaView
} from 'react-native';
import { useRouter } from 'expo-router';
import { 
  ChevronLeft, 
  Share2, 
  Calendar, 
  ChevronRight, 
  TrendingUp, 
  DollarSign, 
  PieChart,
  Anchor
} from 'lucide-react-native';

// --- MOCK CONTEXT (Replace with your actual import) ---
// import { useApp } from '@/context/AppContext';
const useApp = () => {
    // Mocking data for demonstration
    const [lots] = useState([
        { id: '1', boatId: '1', boatName: 'Sea Spirit', species: 'Prawns', weight: 50, pricePerUnit: 400, totalAmount: 20000, commissionAmount: 1000, payableAmount: 19000, timestamp: new Date().setHours(8,0,0,0) },
        { id: '2', boatId: '2', boatName: 'Ocean King', species: 'Mackerel', weight: 120, pricePerUnit: 150, totalAmount: 18000, commissionAmount: 900, payableAmount: 17100, timestamp: new Date().setHours(9,30,0,0) },
        { id: '3', boatId: '1', boatName: 'Sea Spirit', species: 'Tuna', weight: 30, pricePerUnit: 800, totalAmount: 24000, commissionAmount: 1200, payableAmount: 22800, timestamp: new Date().setHours(10,15,0,0) },
    ]);
    return { lots, boats: [] };
};

export default function DailyScreen() {
    const router = useRouter();
    const { lots } = useApp();
    
    // State for Date Navigation
    const [selectedDate, setSelectedDate] = useState(new Date());

    // --- CALCULATIONS ---
    const dailyStats = useMemo(() => {
        const startOfDay = new Date(selectedDate);
        startOfDay.setHours(0, 0, 0, 0);
        
        const endOfDay = new Date(selectedDate);
        endOfDay.setHours(23, 59, 59, 999);

        const daysLots = lots.filter(lot => 
            lot.timestamp >= startOfDay.getTime() && 
            lot.timestamp <= endOfDay.getTime()
        );

        const revenue = daysLots.reduce((sum, lot) => sum + lot.totalAmount, 0);
        const commission = daysLots.reduce((sum, lot) => sum + lot.commissionAmount, 0);
        const payable = daysLots.reduce((sum, lot) => sum + lot.payableAmount, 0);

        // Species Grouping
        const speciesMap: Record<string, { weight: number; amount: number; count: number }> = {};
        daysLots.forEach(lot => {
            if (!speciesMap[lot.species]) {
                speciesMap[lot.species] = { weight: 0, amount: 0, count: 0 };
            }
            speciesMap[lot.species].weight += lot.weight;
            speciesMap[lot.species].amount += lot.totalAmount;
            speciesMap[lot.species].count += 1;
        });

        // Convert to array and sort by weight for the progress bars
        const speciesList = Object.entries(speciesMap)
            .map(([name, stats]) => ({ name, ...stats }))
            .sort((a, b) => b.weight - a.weight);

        const maxWeight = speciesList.length > 0 ? speciesList[0].weight : 1;

        return { 
            daysLots, 
            revenue, 
            commission, 
            payable, 
            speciesList, 
            maxWeight 
        };
    }, [selectedDate, lots]);

    // --- HANDLERS ---
    const changeDate = (days: number) => {
        const newDate = new Date(selectedDate);
        newDate.setDate(newDate.getDate() + days);
        setSelectedDate(newDate);
    };

    const handleShare = async () => {
        const dateStr = selectedDate.toDateString();
        const message = `
📊 *DAILY REPORT - ${dateStr}*
--------------------------------
💰 *Gross Revenue:* ₹${dailyStats.revenue.toLocaleString()}
🏷️ *Commission:* ₹${dailyStats.commission.toLocaleString()}
✅ *Net Payable:* ₹${dailyStats.payable.toLocaleString()}

🐟 *Catch Summary:*
${dailyStats.speciesList.map(s => `• ${s.name}: ${s.weight}kg (₹${s.amount.toLocaleString()})`).join('\n')}

📝 *Total Transactions:* ${dailyStats.daysLots.length}
--------------------------------
Generated by AquaLedger
        `.trim();

        try {
            await Share.share({ message });
        } catch (error) {
            Alert.alert('Error', (error as Error).message);
        }
    };

    return (
        <SafeAreaView style={styles.safeArea}>
            <StatusBar barStyle="light-content" backgroundColor="#0B0B15" />
            
            <View style={styles.container}>
                {/* --- HEADER --- */}
                <View style={styles.header}>
                    <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
                        <ChevronLeft size={24} color="#FFF" />
                    </TouchableOpacity>
                    <Text style={styles.headerTitle}>Daily Summary</Text>
                    <TouchableOpacity onPress={handleShare} style={styles.shareButton}>
                        <Share2 size={20} color="#FFF" />
                    </TouchableOpacity>
                </View>

                <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
                    
                    {/* --- DATE NAVIGATOR --- */}
                    <View style={styles.dateNavContainer}>
                        <TouchableOpacity onPress={() => changeDate(-1)} style={styles.navArrow}>
                            <ChevronLeft size={20} color="#666" />
                        </TouchableOpacity>
                        
                        <View style={styles.dateDisplay}>
                            <Calendar size={16} color="#246BFD" style={{ marginRight: 8 }} />
                            <Text style={styles.dateText}>
                                {selectedDate.toDateString() === new Date().toDateString() 
                                    ? "Today, " + selectedDate.toLocaleDateString(undefined, {month:'short', day:'numeric'}) 
                                    : selectedDate.toDateString()}
                            </Text>
                        </View>

                        <TouchableOpacity onPress={() => changeDate(1)} style={styles.navArrow}>
                            <ChevronRight size={20} color="#666" />
                        </TouchableOpacity>
                    </View>

                    {/* --- FINANCIAL GRID --- */}
                    <View style={styles.statsGrid}>
                        {/* Revenue */}
                        <View style={styles.statCard}>
                            <View style={[styles.iconBg, { backgroundColor: 'rgba(36, 107, 253, 0.15)' }]}>
                                <TrendingUp size={20} color="#246BFD" />
                            </View>
                            <Text style={styles.statLabel}>Revenue</Text>
                            <Text style={styles.statValue}>₹{(dailyStats.revenue / 1000).toFixed(1)}k</Text>
                        </View>

                        {/* Commission */}
                        <View style={styles.statCard}>
                            <View style={[styles.iconBg, { backgroundColor: 'rgba(255, 87, 95, 0.15)' }]}>
                                <PieChart size={20} color="#FF575F" />
                            </View>
                            <Text style={styles.statLabel}>Comm.</Text>
                            <Text style={[styles.statValue, { color: '#FF575F' }]}>₹{(dailyStats.commission / 1000).toFixed(1)}k</Text>
                        </View>

                        {/* Payable */}
                        <View style={styles.statCard}>
                            <View style={[styles.iconBg, { backgroundColor: 'rgba(147, 217, 78, 0.15)' }]}>
                                <DollarSign size={20} color="#93D94E" />
                            </View>
                            <Text style={styles.statLabel}>Net Pay</Text>
                            <Text style={[styles.statValue, { color: '#93D94E' }]}>₹{(dailyStats.payable / 1000).toFixed(1)}k</Text>
                        </View>
                    </View>

                    {/* --- SPECIES BREAKDOWN (With Visual Bars) --- */}
                    <Text style={styles.sectionTitle}>Catch Analysis</Text>
                    <View style={styles.sectionCard}>
                        {dailyStats.speciesList.length > 0 ? (
                            dailyStats.speciesList.map((item, index) => (
                                <View key={index} style={styles.speciesRow}>
                                    <View style={styles.speciesHeader}>
                                        <Text style={styles.speciesName}>{item.name}</Text>
                                        <Text style={styles.speciesAmount}>₹{item.amount.toLocaleString()}</Text>
                                    </View>
                                    <View style={styles.progressBarContainer}>
                                        <View 
                                            style={[
                                                styles.progressBar, 
                                                { width: `${(item.weight / dailyStats.maxWeight) * 100}%` }
                                            ]} 
                                        />
                                    </View>
                                    <Text style={styles.speciesDetail}>{item.weight} kg • {item.count} lots</Text>
                                </View>
                            ))
                        ) : (
                            <Text style={styles.emptyText}>No data for this date</Text>
                        )}
                    </View>

                    {/* --- TRANSACTION LIST --- */}
                    <Text style={styles.sectionTitle}>Transactions</Text>
                    <View style={{ gap: 12 }}>
                        {dailyStats.daysLots.map((lot) => (
                            <View key={lot.id} style={styles.transactionCard}>
                                <View style={styles.transLeft}>
                                    <View style={styles.boatIconSmall}>
                                        <Anchor size={16} color="#AAA" />
                                    </View>
                                    <View>
                                        <Text style={styles.transBoat}>{lot.boatName}</Text>
                                        <Text style={styles.transTime}>
                                            {new Date(lot.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} • {lot.species}
                                        </Text>
                                    </View>
                                </View>
                                <View style={styles.transRight}>
                                    <Text style={styles.transAmount}>₹{lot.totalAmount.toLocaleString()}</Text>
                                    <Text style={styles.transWeight}>{lot.weight}kg</Text>
                                </View>
                            </View>
                        ))}
                         {dailyStats.daysLots.length === 0 && (
                            <Text style={styles.emptyText}>No transactions found.</Text>
                        )}
                    </View>

                </ScrollView>
            </View>
        </SafeAreaView>
    );
}

const styles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: "#0B0B15" },
    container: { flex: 1, backgroundColor: "#0B0B15" },
    
    // Header
    header: { 
        paddingHorizontal: 20, 
        paddingBottom: 20, 
        flexDirection: "row", 
        alignItems: "center", 
        justifyContent: "space-between",
        marginTop: 30 // Top Margin for Back Button
    },
    backButton: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center', borderRadius: 20, backgroundColor: '#181822', borderWidth: 1, borderColor: '#2A2A35' },
    headerTitle: { fontSize: 18, fontWeight: '700', color: '#FFF' },
    shareButton: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center', borderRadius: 20, backgroundColor: '#246BFD' },

    scrollContent: { paddingHorizontal: 20, paddingBottom: 50 },

    // Date Navigation
    dateNavContainer: { 
        flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', 
        backgroundColor: '#181822', borderRadius: 16, padding: 8, marginBottom: 24,
        borderWidth: 1, borderColor: '#2A2A35'
    },
    navArrow: { padding: 10 },
    dateDisplay: { flexDirection: 'row', alignItems: 'center' },
    dateText: { color: '#FFF', fontSize: 16, fontWeight: '600' },

    // Financial Grid
    statsGrid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24, gap: 12 },
    statCard: { 
        flex: 1, backgroundColor: '#181822', borderRadius: 16, padding: 12, 
        alignItems: 'center', borderWidth: 1, borderColor: '#2A2A35' 
    },
    iconBg: { width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
    statLabel: { color: '#AAA', fontSize: 12, marginBottom: 4 },
    statValue: { color: '#FFF', fontSize: 16, fontWeight: '700' },

    // Sections
    sectionTitle: { fontSize: 18, fontWeight: '700', color: '#FFF', marginBottom: 12, marginTop: 8 },
    sectionCard: { backgroundColor: '#181822', borderRadius: 20, padding: 20, borderWidth: 1, borderColor: '#2A2A35', marginBottom: 24 },
    
    // Species Rows
    speciesRow: { marginBottom: 16 },
    speciesHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
    speciesName: { color: '#FFF', fontSize: 14, fontWeight: '600' },
    speciesAmount: { color: '#AAA', fontSize: 14 },
    progressBarContainer: { height: 6, backgroundColor: '#2A2A35', borderRadius: 3, marginBottom: 6 },
    progressBar: { height: '100%', backgroundColor: '#246BFD', borderRadius: 3 },
    speciesDetail: { color: '#666', fontSize: 10 },

    // Transactions
    transactionCard: { 
        flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
        backgroundColor: '#181822', padding: 16, borderRadius: 16,
        borderWidth: 1, borderColor: '#2A2A35'
    },
    transLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    boatIconSmall: { width: 32, height: 32, borderRadius: 10, backgroundColor: '#2A2A35', justifyContent: 'center', alignItems: 'center' },
    transBoat: { color: '#FFF', fontSize: 14, fontWeight: '600' },
    transTime: { color: '#666', fontSize: 12 },
    transRight: { alignItems: 'flex-end' },
    transAmount: { color: '#93D94E', fontSize: 14, fontWeight: '700' },
    transWeight: { color: '#AAA', fontSize: 12 },

    emptyText: { color: '#666', textAlign: 'center', fontStyle: 'italic', padding: 20 }
});